sudo: required
language: node_js
addons:
  apt:
    sources:
    - sourceline: 'ppa:ondrej/php'
    packages:
    - php7.0-cli
install:
  - npm install -g firebase-tools
script:
  - ./build.sh
after_success:
  - echo not deploying, we use git watch instead.
  #- firebase deploy --token=${FIREBASE_CI_TOKEN} --project scalawilliam-ff4b2
dist: trusty
cache:
  directories:
    - $HOME/.npm

